[build-system]
requires = ["maturin>=1.10,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "src"
module-name = "change_point_algorithms._change_point_algorithms"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[project]
name = "change_point_algorithms"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
readme = "README.md"

dependencies = [ # need it for saving plots from plotly
    "matplotlib", # plotting library
    "maturin",
    "numba", # speeding up some python functions
    "numpy",
    "pandas", # plotting library
    "scikit-learn",
    "scipy",
    "ruptures", # offline change point detection
    "tomlkit",
    "typer>=0.17.4",
    "polars>=1.33.1",
    "more-itertools>=10.8.0",
]

[project.optional-dependencies]
testing = [
    "pytest",
    "pytest-benchmark"
]
profiling = [
    "line_profiler",
    "snakeviz",
    "jinja2"
]
progress = [
    "tqdm" # progress bars
]
